"""Adding asset and debt take2 first attempt failed

Revision ID: 38d9584aec2f
Revises: 41db1775701b
Create Date: 2026-07-11 16:53:00.544077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d9584aec2f'
down_revision: Union[str, Sequence[str], None] = '41db1775701b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_assets', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('total_debt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_debt')
    op.drop_column('users', 'total_assets')
    # ### end Alembic commands ###
